-- A monotonic position for the status timeline.
--
-- The timeline was ordered by created_at alone. H2's TIMESTAMP keeps no fractional seconds, so two
-- events recorded in the same second tie, and the database is free to return either first. A resident
-- reading an audit trail to judge whether a municipality responded cannot be shown two identical
-- requests in different orders, and the ordering a user sees should not depend on the storage engine.
--
-- PostgreSQL keeps microseconds, which is why this never surfaced in development and only appeared
-- running the suite on H2. A latent defect, not a new one.
--
-- Existing rows are ordered by (created_at, id) so their sequence is monotonic too, even though the
-- true order between two rows written in the same second was never recorded and cannot be recovered.

ALTER TABLE signal_status_history
    ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Backfilled with a correlated count rather than row_number() OVER (...): this migration runs on
-- H2 for the suite as well as PostgreSQL, and H2 rejects a window function in an UPDATE SET clause.
UPDATE signal_status_history h
   SET seq = (SELECT COUNT(*)
                FROM signal_status_history o
               WHERE o.created_at < h.created_at
                  OR (o.created_at = h.created_at AND o.id < h.id));

-- Older rows need a value that is lower than anything the identity column will hand out next.
ALTER TABLE signal_status_history ALTER COLUMN seq RESTART WITH 1000000;

CREATE INDEX idx_signal_status_history_signal_seq
    ON signal_status_history (signal_id, seq DESC);