import { expect, test } from '@playwright/test';

test.describe('Dashboard Detail Navigation (P0)', () => {
  test('dashboard row opens detail and can return to dashboard', async ({ page }) => {
    const signalTitle = `Playwright nav signal ${Date.now()}`;

    await page.goto('/login');
    await page.getByTestId('login-username-input').fill('admin');
    await page.getByTestId('login-password-input').fill('admin12345');
    await page.getByTestId('login-submit-button').click();

    await page.waitForURL('**/');
    await page.goto('/report');
    await page.locator('#title').fill(signalTitle);
    await page.locator('#description').fill('Signal generated by E2E to validate dashboard-to-detail navigation.');
    await page.locator('#category').click();
    await page.locator('.p-dropdown-item').first().click();
    await page.getByRole('button', { name: /Ingest Signal|Submit|Ingresar/ }).click();

    await page.waitForURL('**/');
    await expect(page.getByTestId('signals-datatable')).toBeVisible();
    await expect(page.locator('.p-skeleton')).toHaveCount(0);
    await expect(page.getByTestId('signals-datatable')).toContainText(signalTitle);

    const firstRow = page.locator('[data-testid="signals-datatable"] tbody tr').first();
    await expect(firstRow).toBeVisible();
    await firstRow.click();

    await expect(page).toHaveURL(/\/signal\/[0-9a-f-]{36}$/);
    await expect(page.getByTestId('signal-detail-view')).toBeVisible();
    await expect(page.getByTestId('signal-title')).toBeVisible();
    await expect(page.getByTestId('priority-score-card')).toBeVisible();
    await expect(page.getByTestId('why-ranked-panel')).toBeVisible();
    await expect(page.getByTestId('why-ranked-panel')).toContainText(/Why Ranked Here|Por que esta aqui/);

    await page.getByTestId('signal-detail-back-button').click();
    await expect(page).toHaveURL(/\/$/);
    await expect(page.getByTestId('signals-datatable')).toBeVisible();
  });
});
