package org.opencivic.signalos.domain;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "signal_status_history")
public class SignalStatusEntry {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false)
    private UUID signalId;

    @Column(nullable = false)
    private String statusFrom;

    @Column(nullable = false)
    private String statusTo;

    @Column(nullable = false)
    private String eventType = "STATUS_CHANGED";

    private String changedBy;

    private String assignedToUsername;
    
    @Column(columnDefinition = "TEXT")
    private String reason;

    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * Insertion order, when the engine records one.
     *
     * <p>The timeline used to be ordered by {@code createdAt} alone, which ties on any engine whose
     * timestamps have no fractional seconds. A tie means the database may return either event first,
     * so the same two requests render in a different order from one run to the next.
     *
     * <p>{@code columnDefinition} repeats the clause V50 declares, and it is the whole fix. The suite
     * sets {@code ddl-auto: create-drop}, so Hibernate drops whatever Flyway built and recreates every
     * table from the entities - and the recreated column was a plain {@code bigint} with no default.
     * Nothing ever assigned to it, {@code seq} came back null on every row, and
     * {@code order by ... coalesce(e.seq, 0) desc} quietly degraded to ordering by timestamp alone: the
     * defect V50 exists to prevent, passing every test in the suite. Spelling the column out makes the
     * generated schema carry the identity, on H2 and on PostgreSQL alike.
     */
    @Column(
        name = "seq",
        insertable = false,
        updatable = false,
        columnDefinition = "bigint generated by default as identity"
    )
    private Long seq;

    public Long getSeq() {
        return seq;
    }

    public SignalStatusEntry() {}

    public SignalStatusEntry(UUID signalId, String statusFrom, String statusTo, String changedBy, String reason) {
        this(signalId, statusFrom, statusTo, "STATUS_CHANGED", changedBy, reason, null);
    }

    public SignalStatusEntry(
        UUID signalId,
        String statusFrom,
        String statusTo,
        String eventType,
        String changedBy,
        String reason,
        String assignedToUsername
    ) {
        this.signalId = signalId;
        this.statusFrom = statusFrom;
        this.statusTo = statusTo;
        this.eventType = eventType;
        this.changedBy = changedBy;
        this.reason = reason;
        this.assignedToUsername = assignedToUsername;
    }

    public UUID getId() { return id; }
    public UUID getSignalId() { return signalId; }
    public String getStatusFrom() { return statusFrom; }
    public String getStatusTo() { return statusTo; }
    public String getEventType() { return eventType; }
    public String getChangedBy() { return changedBy; }
    public String getAssignedToUsername() { return assignedToUsername; }
    public String getReason() { return reason; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
